title:  airman604
author: airman604
description: >
  Random rumblings about #InfoSec. The opinions expressed are my own.

theme: jekyll-theme-cayman

# social links
twitter_username: airman604 # DO NOT include the @ character, or else the build will fail!
github_username:  airman604 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage